services:
  service1:
    build:
      context: ./llamaApp
    ports:
      - "11431:11434"

  service2:
    build:
      context: ./mistralApp
    ports:
      - "11433:11434"

  service3:
    build:
      context: ./phi3App
    ports:
      - "11432:11434"

  # service4:
  #   build:
  #     context: ./server
  #   ports:
  #     - "5000:5000"